export const MEV_AUCTION_HOOK_ABI = [
  {
    type: "function",
    name: "auctionWindowBlocks",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "smallSwapThreshold",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextRequestId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingRefunds",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestSwap",
    inputs: [
      {
        name: "key",
        type: "tuple",
        components: [
          { name: "currency0", type: "address" },
          { name: "currency1", type: "address" },
          { name: "fee", type: "uint24" },
          { name: "tickSpacing", type: "int24" },
          { name: "hooks", type: "address" },
        ],
      },
      {
        name: "params",
        type: "tuple",
        components: [
          { name: "zeroForOne", type: "bool" },
          { name: "amountSpecified", type: "int256" },
          { name: "sqrtPriceLimitX96", type: "uint160" },
        ],
      },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "submitBid",
    inputs: [
      { name: "requestId", type: "uint256" },
      { name: "bidAmount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "cancelSwap",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeSwap",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawRefund",
    inputs: [{ name: "currencyAddress", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRequestInfo",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [
      {
        name: "info",
        type: "tuple",
        components: [
          { name: "sender", type: "address" },
          { name: "currency0", type: "address" },
          { name: "currency1", type: "address" },
          { name: "zeroForOne", type: "bool" },
          { name: "amountSpecified", type: "int256" },
          { name: "deadlineBlock", type: "uint256" },
          { name: "highestBid", type: "uint256" },
          { name: "highestBidder", type: "address" },
          { name: "isCompleted", type: "bool" },
          { name: "auctionOpen", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "SwapRequested",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "sender", type: "address", indexed: true },
      { name: "inputAmount", type: "uint256", indexed: false },
      { name: "deadlineBlock", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BidSubmitted",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "bidder", type: "address", indexed: true },
      { name: "bidAmount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SwapExecuted",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "donatedAmount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SwapCancelled",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "sender", type: "address", indexed: true },
      { name: "refundedAmount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyExecuted", inputs: [] },
  { type: "error", name: "AuctionAlreadyClosed", inputs: [] },
  { type: "error", name: "AuctionStillOpen", inputs: [] },
  { type: "error", name: "BidTooLow", inputs: [] },
  { type: "error", name: "BidsAlreadySubmitted", inputs: [] },
  { type: "error", name: "DirectSwapNotAllowed", inputs: [] },
  { type: "error", name: "NoRefundAvailable", inputs: [] },
  { type: "error", name: "NotRequester", inputs: [] },
  { type: "error", name: "OnlyExactIn", inputs: [] },
  { type: "error", name: "RequestNotFound", inputs: [] },
  { type: "error", name: "UnexpectedETH", inputs: [] },
  { type: "error", name: "WrongETHAmount", inputs: [] },
] as const;
